@OrderProcessing.API_HostAddress = http://localhost:5210

POST {{OrderProcessing.API_HostAddress}}/orders/
Content-Type: application/json

{
    "orderId": "123456",
    "products": [
      {
        "productId": "123",
        "quantity": 2
      },
      {
        "productId": "456",
        "quantity": 5
      }
    ]
}
###
